all:
    hosts:
    children:
        webserver:
            hosts:
                80vps.yangjian.net:7117
        vpnserver:
            hosts:
                80vps.yangjian.net:7117
                aws.yangjian.net:7117
                bw.yangjian.net:7117
        hk:
            hosts:
                80vps.yangjian.net:7117
        us:
            hosts:
                aws.yangjian.net:7117
                bw.yangjian.net:7117
